# Generated by Django 3.1.4 on 2021-11-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211128_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='marksObtained',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
